# Generated by Django 2.2 on 2019-04-29 08:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('overview', models.TextField(default='')),
                ('git_link', models.CharField(default='none', max_length=250)),
                ('over', models.FileField(default=0, upload_to='')),
                ('view_count', models.IntegerField(default=0)),
                ('content', tinymce.models.HTMLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cover_image', models.ImageField(upload_to='images/')),
                ('tags', models.ManyToManyField(to='blog.Tag')),
            ],
        ),
    ]
