# Generated by Django 2.2 on 2019-05-01 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(default='Haritz Laboa', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('overview', models.TextField(default='')),
                ('content', tinymce.models.HTMLField()),
                ('cover_image', models.ImageField(upload_to='images/')),
                ('cover_author', models.CharField(default='', max_length=200)),
                ('git_link', models.CharField(default='none', max_length=250)),
                ('view_count', models.IntegerField(default=0)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Author')),
                ('language', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Language')),
                ('tags', models.ManyToManyField(to='blog.Tag')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
