# Generated by Django 2.2 on 2019-05-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190501_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover_image',
            new_name='overview_image',
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='none', upload_to='images/'),
        ),
    ]
