# Generated by Django 2.2 on 2019-05-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190502_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
