# Generated by Django 2.2 on 2019-05-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_cover_author_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='language',
        ),
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.ManyToManyField(default=1, to='blog.Language'),
        ),
    ]
