# Generated by Django 2.2 on 2019-05-02 21:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190502_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('español', tinymce.models.HTMLField()),
                ('english', tinymce.models.HTMLField()),
            ],
        ),
    ]
